### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by AH-Huynh942** [AH-Huynh942/portfolio-website#1]
# Summary

There should be clickable textbuttons that when pressed, will direct you to different parts of the site (whether just scrolling down or a different route). The navbar should disappear on the top be show up when you scroll down. Could be vertical or horizontal.

# Description

This feature is needed to allow the user to correctly navigate to all parts of the website with ease. Simply shows textbuttons with a logo. Clinking on text buttons redirects. Does an animation that slows straight up when you scroll to the top.

# Requirements

- [x] Figure out how to show an horizontal contrasting colored bar on the top of the page. 
- [x] Figure out how to occupy horizontal *box with buttons, images, logos etc...
- [x] Figure out how to space the elements (logo at start textbutton in the middle) properly
- [x] Figure out the slide animation when the navbar dissappears on scrolling
- [x] Figure out how to make buttons on press move to the other parts of website (whole new page for now)

# Tasks

- [x] Program horizontal box to STICK to the top
- [x] Added textbutton elements and space properly (may want to do with the different sizes)
- [x] Space out with maybe HTML CSS?
- [x] Program redirection functionality
