### ISSUE TITLE
Projects section

### ISSUE THREAD

**Issue by AH-Huynh942** [AH-Huynh942/portfolio-website#3]
# Summary

A section with clickable image buttons that will redirect to my cool and awesome projects

# Description

This is the main thing I want the recruiter to see! Very important! _**Clearly**_ shows the projects in a _standout_ kind of way.
Ultimately this will redirect the recruiter to one of my project pages/github_page/etc...

Might be a carousel? Circle? What do I want to make it look cool? Brain image? Buttons need to really popout!

# Requirements

- [x] Must make a bunch of image buttons that will show ALL my projects
- [ ] To stand out, when the buttons are hovered over, they show a different button pass
- [ ] Lookat some plugins like the carousel, brain image???, fadeout stuff?

# Tasks

- [ ] Integrate the carousel into my website
- [x] Image button clicked will redirect the project page
- [ ] Program button hover CSS
